### ISSUE TITLE
Job control

### ISSUE THREAD

**Issue by emersion** [emersion/mrsh#1]

**Comment by SirCmpwn** [comment]
>-m: This option shall be supported if the implementation supports the User Portability Utilities option. All jobs shall be run in their own process groups. Immediately before the shell issues a prompt after completion of the background job, a message reporting the exit status of the background job shall be written to standard error. If a foreground job stops, the shell shall write a message to standard error to that effect, formatted as described by the jobs utility. In addition, if a job changes status other than exiting (for example, if it stops for input or output or is stopped by a SIGSTOP signal), the shell shall write a similar message immediately prior to writing the next prompt. This option is enabled by default for interactive shells.

Related:

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/bg.html

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/fg.html

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/kill.html

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/wait.html

**Comment by emersion** [comment]
Some docs: https://www.gnu.org/software/libc/manual/html_node/Job-Control.html#Job-Control

**Comment by emersion** [comment]
First step would be to make the glibc manual code work: https://git.sr.ht/~emersion/minishell

**Comment by emersion** [comment]
Job control has been mostly sorted out now. Two builtins have been implemented: `fg` and `bg`. Other builtins will be easy to implement.

**Comment by emersion** [comment]
- [ ] Check disabling job control does the right thing
- [ ] Store the AST that started each job (required for pretty-printing it)
- [ ] Add support for `fg` and `bg` optional argument
- [ ] Add `kill`, `wait`

**Comment by emersion** [comment]
To store the AST, I think I'll make `mrsh_job` able to contain zero jobs so that we can create the job when executing the pipeline or async list.

**Comment by emersion** [comment]
Jobs now store the AST node they have been created for.

**Comment by ddevault** [comment]
Nice ^^

**Comment by emersion** [comment]
Job control has been almost completely sorted out by now, the complicated part is implemented. I've opened separate issues for the remaining bits.
