### ISSUE TITLE
For loop doesn't iterate over words split by IFS

### ISSUE THREAD

**Issue by apiote** [emersion/mrsh#125]
After reading the specification linked in mrsh status, I don't know if IFS splitting applies in for loops, but both dash and bash as sh iterate.

Example:
```
$ x='1:2:3'
$ IFS=':'; for p in $x; do echo $p; done
```

In mrsh the result is
```
1 2 3
```
In both bash as sh and dash the result is
```
1
2
3
```

**Comment by emersion** [comment]
Hmm, indeed, `$x` doesn't get expanded into multiple fields it seems. This works:

```sh
for p in a b c; do echo $p; done
```

Pretty sure your version used to work at some point. Will add a test for it.
