### ISSUE TITLE
readonly: Readonly variables don't appear in 'readonly -p'

### ISSUE THREAD

**Issue by dylanaraps** [emersion/mrsh#133]
Possibly related to #132.

Other shells (All identical):

```sh
-> test="Hello World"
-> readonly test
-> readonly -p
readonly test='Hello World'
```

`mrsh`:

I'm using grep due to #132 and it finds no matches as the now `readonly` variable `test` isn't in the output.

```sh
-test="Hello World"
-readonly test
-readonly -p | grep test 
-
```

**Comment by emersion** [comment]
Also fixed by https://github.com/emersion/mrsh/commit/82d450de5967d1fb2144d3181c616a428928fa1c
