### ISSUE TITLE
builtin/exec: add support for no argument

### ISSUE THREAD

**Issue by emersion** [emersion/mrsh#136]
Not sure how to interpret this part of the spec:

> If exec is specified without command or arguments, and any file descriptors with numbers greater than 2 are opened with associated redirection statements, it is unspecified whether those file descriptors remain open when the shell invokes another utility. 

Does that mean using `exec` to open FDs is undefined behaviour?

**Comment by ddevault** [comment]
Hm, I think that interpretation is correct. Which is pretty lame.
