### ISSUE TITLE
Complete trap(1) support

### ISSUE THREAD

**Issue by emersion** [emersion/mrsh#137]
- [x] Signals that were ignored on  entry  to  a  non-interactive  shell  cannot  be
       trapped or reset
- [x] When a subshell is entered, traps that are not being ignored shall be  set  to
       the  default  actions, except in the case of a command substitution containing
       only a single trap command, when the traps need not  be  altered.
- [x] Proper quoting when printing traps
- [x] The value of "$?" after the trap action completes shall be the value it had before
       trap was invoked.
- [x] Fix interactions with job control

**Comment by ddevault** [comment]
:tada:
