### ISSUE TITLE
Wrong begining position for arguments in commands

### ISSUE THREAD

**Issue by tomleb** [emersion/mrsh#140]
When printing the AST, we can see that the beginning of the range of word_string's is wrong.
It is always set to the parser position. The [mrsh_position_valid()] check always goes inside the if statement because the line is 0.

I am not sure how to fix that because I am not sure what `mrsh_position_valid` is supposed to validate. Looking at [struct mrsh_position], the comment says that line should start at 1, but for the parser it starts at 0.

[struct mrsh_position]: https://git.sr.ht/~emersion/mrsh/tree/master/include/mrsh/ast.h#L11

[mrsh_position_valid()]: https://git.sr.ht/~emersion/mrsh/tree/master/parser/word.c#L642

Here is an example:

```
$ echo "echo hi ok" | ./build/mrsh -n 
program
└─command_list ─ pipeline
  └─simple_command
    ├─name ─ word_string [0:0 → 0:4] echo
    ├─argument 1 ─ word_string [0:7 → 0:7] hi
    └─argument 2 ─ word_string [0:10 → 0:10] ok
```

I am assuming this should be an easy fix, so if you're willing to tell me what `mrsh_position_valid` really should do, I could prepare a patch. That'd be my first introduction to this project.

This check also happens at a few other places (eg: `arithmetic_word`, `parameter_expansion_word`).

**Comment by emersion** [comment]
`mrsh_position_valid` should tell whether a `mrsh_position` is set or unset. A zero-initialized `mrsh_position` basically means "unknown position".

A valid line number should always be >= 1. Maybe we don't initialize it properly somewhere?

**Comment by tomleb** [comment]
For some reason, I'm unable to reproduce it.

Even using the commits I was previously using, I'm not getting this behavior at all.

I guess it is safe to close this issue.
