### ISSUE TITLE
builtin read should return >0 if it gets an EOF

### ISSUE THREAD

**Issue by annacrombie** [emersion/mrsh#142]
In other shells, I often do something like the following

```sh
generate_input | while read line; do echo "got $line"; done
```

In mrsh, the loop never ends since `read` always returns 0 if it is called properly.

After looking over [this](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/read.html), it seems like `read` should indeed return >0 in this case.

**Comment by emersion** [comment]
Indeed. Lines ending with EOF should make `read` return >0:

```sh
> printf "line1\\nline2"  | while read line; do echo "got $line"; done
got line1
```

Would you be willing to write a patch to `builtin/read.c` to fix this?

**Comment by annacrombie** [comment]
I would be interested in doing it for sure!  I'll see what I can come up with.  Do you have a preference for patches via github or sourcehut?

**Comment by emersion** [comment]
Cool! Use whatever you're more comfortable with. Feel free to ask questions on IRC in `##emersion` if you're not familiar with the SourceHut workflow.
