### ISSUE TITLE
$HOME/.mrsh_history isn't getting created

### ISSUE THREAD

**Issue by inet56** [emersion/mrsh#182]
`Linux fedora 5.11.12-300.fc34.x86_64 #1 SMP Wed Apr 7 16:31:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux` <br>
`commit 9f9884083831ea1f94bdda5151c5df3888932849`

**Comment by emersion** [comment]
It only gets created when compiled with readline.
