### ISSUE TITLE
Reimplement wordexp

### ISSUE THREAD

**Issue by emersion** [emersion/mrsh#32]
https://git.musl-libc.org/cgit/musl/tree/src/misc/wordexp.c

**Comment by emersion** [comment]
Scratch that, we already have a `wordexp` implementation. I mixed things up with `glob`. So we're safe, we won't call a function that executes ourselves.

**Comment by SirCmpwn** [comment]
I still think it's on-topic for mrsh to have a wordexp implementation, given that musl doesn't have access to mrsh's variables or anything

**Comment by emersion** [comment]
>we already have a wordexp implementation

**Comment by SirCmpwn** [comment]
oh
