### ISSUE TITLE
Line break missing

### ISSUE THREAD

**Issue by zapashcanon** [emersion/mrsh#34]
Hi,

From your favorite shell:

`build/mrsh`

Then, from mrsh:

`build/mrsh`

Then, exit the last one. You get something like `$ $` printed, because a line break is missing.

**Comment by emersion** [comment]
I'm not sure this is a bug actually. Trying the same thing in `dash`, I can reproduce too.

**Comment by zapashcanon** [comment]
Oh, I couldn't reproduce with `sh`.

**Comment by emersion** [comment]
`sh` is likely to be a symlink to bash on your system. Since bash isn't POSIX-compliant its probably not a good idea to use it as a reference implementation.

**Comment by zapashcanon** [comment]
Nah, I checked, it's linked to `dash`...

**Comment by SirCmpwn** [comment]
I can reproduce with dash. It's not really a bug.

**Comment by emersion** [comment]
Fixed by https://lists.sr.ht/%7Eemersion/public-inbox/%3C20180929202718.3107-1-sir%40cmpwn.com%3E#%3C20180929202718.3107-2-sir@cmpwn.com%3E

**Comment by zapashcanon** [comment]
Great ! (I get a 404 if I follow your link, do I need an account or something ?)

**Comment by SirCmpwn** [comment]
https://lists.sr.ht/~emersion/mrsh-dev/%3C20180929202718.3107-1-sir%40cmpwn.com%3E#%3C20180929202718.3107-2-sir@cmpwn.com%3E

The mailing list was migrated today

**Comment by zapashcanon** [comment]
Thanks !
