### ISSUE TITLE
Segfault on assigning variable to empty value

### ISSUE THREAD

**Issue by delthas** [emersion/mrsh#44]
- open a shell, enter `CC=` (or any other variable)
- expected behaviour: the shell sets `CC` to the empty string (or unsets it)
- actual behaviour: segfault (`assign->value` is `NULL` at ast.c:665)

**Comment by emersion** [comment]
This seems like a bug in the parser. We should set `assign->value` to `strdup("")` when there's no value while parsing an assignment.
