### ISSUE TITLE
Associativity in arithmetic expressions

### ISSUE THREAD

**Issue by emersion** [emersion/mrsh#53]
Some operators have the wrong associativity. See

* https://en.cppreference.com/w/c/language/operator_precedence
* https://eli.thegreenplace.net/2009/03/14/some-problems-of-recursive-descent-parsers
* https://github.com/mvdan/sh/blob/master/syntax/parser.go#L1061

**Comment by mvdan** [comment]
By the way, if you encounter bugs or confusing code in my shell package, feel free to reach out :)

**Comment by emersion** [comment]
>By the way, if you encounter bugs or confusing code in my shell package, feel free to reach out :)

Eh, thanks! :)

**Comment by emersion** [comment]
I've been playing with associativity on a toy calculator here: https://git.sr.ht/~emersion/arithm-parser/tree/master/calc.c
