### ISSUE TITLE
Function test fails on FreeBSD

### ISSUE THREAD

**Issue by emersion** [emersion/mrsh#57]
See https://builds.sr.ht/~emersion/job/9653

**Comment by SirCmpwn** [comment]
Which write are we looking at?

**Comment by emersion** [comment]
There are two places where in-memory FDs are used:

* When executing command substitution (`$(command)`): https://github.com/emersion/mrsh/blob/5fd1d6ef43ae19fcf5cfbd4b60ea06663613eb7f/shell/task/word.c#L58  
  We create an in-memory FD that will be written to by the command.
* Here-documents: https://github.com/emersion/mrsh/blob/5fd1d6ef43ae19fcf5cfbd4b60ea06663613eb7f/shell/task/command_process.c#L12
  We write the contents of here-documents to a file that will be read later by exec'ed commands.

In both cases we can use pipes but it's less efficient (and less beautiful).

**Comment by SirCmpwn** [comment]
Man, it's dumb that we can't write to an shm_open'd file. I agree that a pipe is probably the way to go.

**Comment by emersion** [comment]
On Linux we could use `memfd_open` which guarantees we can write to it. But yeah, it's not POSIX, so rip.

**Comment by SirCmpwn** [comment]
Thanks!
