### ISSUE TITLE
Arithmetic operations

### ISSUE THREAD

**Issue by emersion** [emersion/mrsh#6]

**Comment by SirCmpwn** [comment]
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_04

**Comment by emersion** [comment]
Implemented in https://github.com/emersion/mrsh/commit/b082c097322a53d6dc5a24dda6065720c027988d

Follow-up issues:
* https://github.com/emersion/mrsh/issues/51
* https://github.com/emersion/mrsh/issues/52
