### ISSUE TITLE
Only source profile if login shell

### ISSUE THREAD

**Issue by emersion** [emersion/mrsh#62]
>A login shell is the first process that executes under your user ID when you log in for an interactive session. The login process tells the shell to behave as a login shell with a convention: passing argument 0, which is normally the name of the shell executable, with a - character prepended (e.g. -bash whereas it would normally be bash. Login shells typically read a file that does things like setting environment variables: /etc/profile and ~/.profile
>
>It's rare to run a non-interactive login shell, but some X settings do that when you log in with a display manager, so as to arrange to read the profile files.

Also need to source `/etc/profile`.

**Comment by SirCmpwn** [comment]
Hm.

**Comment by emersion** [comment]
What do you mean?

**Comment by SirCmpwn** [comment]
I also use my profile for things like defining aliases

**Comment by SirCmpwn** [comment]
What's the source for that quote?

**Comment by SirCmpwn** [comment]
fwiw dash sources the profile every time

**Comment by emersion** [comment]
I don't think dash sources `~/.profile` each time. Tried adding an `echo` to the profile, and dash doesn't seem to execute it on startup.
