### ISSUE TITLE
Figure out how to make break, continue and return work

### ISSUE THREAD

**Issue by emersion** [emersion/mrsh#66]
We want to hijack the current execution flow up to the parent function or loop.

**Comment by ddevault** [comment]
https://lists.sr.ht/~emersion/mrsh-dev/%3C20180929203315.3395-1-sir%40cmpwn.com%3E

**Comment by emersion** [comment]
Another option might be to have a stack of tasks, and walk up the stack until we find a loop or function task.

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/mrsh/commit/03c5cab96c86536545d3a73c672d0c63bfcf1cf4

**Comment by ddevault** [comment]
:D
