### ISSUE TITLE
getopt cannot be reset

### ISSUE THREAD

**Issue by emersion** [emersion/mrsh#69]
POSIX doesn't expose a way to reset `getopt`'s state. This is an issue when we run multiple builtins which use `getopt` in the same shell process. We probably need to roll our own `getopt` implementation.

**Comment by ddevault** [comment]
We should talk to the Austin Group about resetting getopt's state.

**Comment by emersion** [comment]
https://www.mail-archive.com/austin-group-l@opengroup.org/msg03127.html
