### ISSUE TITLE
Some places found by PVS studio

### ISSUE THREAD

**Issue by shlyakpavel** [emersion/mrsh#73]
1. Do not output usage as formatted string. Use a string format (%s) or fputs instead
https://github.com/emersion/mrsh/blob/1af38099508a577e3e312693048bf1148c9ad768/builtin/alias.c#L23
The same to all usages
2. There is no sense in checking `left` against null here. 
https://github.com/emersion/mrsh/blob/1af38099508a577e3e312693048bf1148c9ad768/parser/arithm.c#L215
It has already been checked before:
https://github.com/emersion/mrsh/blob/1af38099508a577e3e312693048bf1148c9ad768/parser/arithm.c#L201-L202
The same code can be found in other places of arithm.c
3. Pointer to local array 'lineno' is stored outside the scope of this array. Such a pointer will become invalid.
https://github.com/emersion/mrsh/blob/1af38099508a577e3e312693048bf1148c9ad768/shell/task/word.c#L153

**Comment by emersion** [comment]
Thanks! Can you send patches to fix those?

**Comment by shlyakpavel** [comment]
@emersion
Of course I can, but I don't know if it happens soon. I'm in a train in the area with a really limited internet access...

**Comment by shlyakpavel** [comment]
@emersion problem 2 seems to be not a cake to fix. Perhaps it is a wrong condition. But should one check `right` instead of `left`?
I believe it **WAS** supposed to be `right` as there is no sense in calling `mrsh_arithm_expr_destroy ` on a null pointer.
So I believe this actually **does** cause bugs as the code logic is totally wrong. This should be reviewed by someone who understands the code deeply.
The other possible reason is that someone did write the same return on error twice. However, is must be really weird as I do not understand the logic. A straightforward fix is possible, but still...
I do not have enough expertise to treat this. I hope someone else works on it.

**Comment by emersion** [comment]
Re issue 2: you're right, I think it's some copypasta and should check for `right` instead.

**Comment by shlyakpavel** [comment]
Problem no. 3 seems to be still in there. Any ideas how to fix it?

**Comment by emersion** [comment]
I think we can move `lineno` outside of the `if`

**Comment by shlyakpavel** [comment]
> I think we can move `lineno` outside of the `if`

Could you plz make a commit yourself? I'm really afraid to break something here
