### ISSUE TITLE
SIGINT should clear/reset the current line for interactive shells

### ISSUE THREAD

**Issue by skeeto** [emersion/mrsh#77]
Interactive shells usually clear/reset the current input when the user presses C-c. It's a handy way to immediately back out of a partial input. Currently mrsh uses the default handler and just exits, which is pretty unfriendly (and really bad for my muscle memory).

It looks like libreadline can do most of the heavy lifting for this feature:  
http://www.delorie.com/gnu/docs/readline/rlman_43.html

**Comment by emersion** [comment]
Yeah, Unfortunately I don't think we can use these, because we are a shell and will setup handlers for these signals for e.g. job control. We'll need to reset readline manually.

**Comment by emersion** [comment]
Fixed in 763feb2ee5dde542b3acca8e7f60b37d755a36d2
