### ISSUE TITLE
GNU GLOBAL support as plugin parser

### ISSUE THREAD

**Issue by bam80** [emersion/mrsh#84]
GNU GLOBAL is extendible indexing system with reference tags support (so not only function definitions but also calls can be tagged).
It would be useful to make a plugin parser based on this project: https://www.gnu.org/software/global/globaldoc_toc.html#Plug_002din.

The same issue for shell parser in Go: https://github.com/mvdan/sh/issues/351

**Comment by ddevault** [comment]
mrsh has a standalone parser you can use to implement this, probably. But it's none of mrsh's business if you do, so this ticket doesn't belong here imo.

**Comment by bam80** [comment]
Well, I just hoped there is some interest in this..

**Comment by ddevault** [comment]
I mean... it sounds cool, but there's not really anything that mrsh needs to do special to support this use-case. You should review the mrsh API. The parser already fully implements the POSIX shell grammar and you can already use it for this use-case.

**Comment by bam80** [comment]
Unfortunately, I have no resources for this work. So I just leave the issue in hope somebody interested and do some reference shim for GLOBAL.
If you do think it's not belong here - no problem, we can close it

**Comment by ddevault** [comment]
No one is going to accomplish your goals for you: give it a shot!
