### ISSUE TITLE
Comparison to dash

### ISSUE THREAD

**Issue by FlyingWombat** [emersion/mrsh#90]
I wasn't sure where else to ask this, so sorry it it's not on topic.  

I am wondering how `mrsh` differs from [`dash`](https://en.wikipedia.org/wiki/Debian_Almquist_shell) in its design and goals.  
It looks like they both seek to be lightweight, strictly POSIX shells. So, what are the differences, and what is the use-case for `mrsh`?

One thing I can think of is that one goal of `mrsh` is to act as a library to build more advanced interactive shells off of. Whereas I'm not sure how easy that would be with `dash`.

**Comment by ddevault** [comment]
dash is not actually strictly POSIX - it has a number of extensions, such as local and substring expansion. mrsh is much more flexible and extensible, and the mrsh codebase is a lot better imo.

**Comment by emersion** [comment]
So, I've been using dash as a reference for writing mrsh. However the source code is a little bit obscure and hard to understand. It also has a lot of little optimizations which doesn't help making it readable. It's not modular and it's very old (aka. has legacy).

I've been trying to build a simpler alternative, and I also see value in having a more modular approach.

**Comment by FlyingWombat** [comment]
OK, so kinda like how Neovim is to Vim, except that it made more sense to start from scratch rather than forking?

**Comment by emersion** [comment]
I'm not very familiar with Neovim's history, but since some of mrsh goals align with dash, I suppose you could say that.
